//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.MySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_ads
    {
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public int author_id { get; set; }
        public int salary_id { get; set; }
    }
}
