//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.MySQL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class job_portalEntities : DbContext
    {
        public job_portalEntities()
            : base("name=job_portalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<job_ad_applications> job_ad_applications { get; set; }
        public virtual DbSet<job_ads> job_ads { get; set; }
        public virtual DbSet<salary> salaries { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
